### ISSUE TITLE
Pagination-related Text

### ISSUE THREAD

**Issue by megantaylor** [superRaytin/paginationjs-site#1]
Is there a way to do something like "Showing 12 - 18 of 36 items" as a line of text above the pagination? Also, a "Show All Items" button?

**Comment by superRaytin** [comment]
Yeah, it's possible. Just put a div above the pagination bar and format it's content with pagination data.

Showing 12 - 18 of 36 items => Showing `from` - `to` of `total` items.

from: `(currentPage - 1) * pageSize + 1`
to: `currentPage * pageSize`
total: `totalNumber`

Here is a demo which may help you: http://codepen.io/superRaytin/pen/rLeWeN?editors=1010

**Comment by megantaylor** [comment]
Perfect, thank you so much!
