### ISSUE TITLE
Pagination for an xml feed in wordpress

### ISSUE THREAD

**Issue by guyb9290** [superRaytin/paginationjs-site#3]
Hi,
Can you help me please?
I’m pulling xml from a remote server via php into an xsl (attached), I want to use your plugin for table sorting and pagination, I get the resultant table by using this php in the wordpress page:

$feeforeviews = file_get_contents ('http://feefoforwordpresswoocommerce.co.uk/feefo-invisibra/feefofeedbackserviceonly-v2-scroll.php?merchantidentifier=invisibra&mode=service&sortby=date&limit=200'); 
                return $feeforeviews;
}

I hope this makes some sense, I just can’t figure out how to get your pagination to work, I've registered your pagination.js in WP in the functions.php

I hope you can help me as your js looks really good

[Saved.zip](https://github.com/superRaytin/paginationjs-site/files/411091/Saved.zip)

**Comment by guyb9290** [comment]
Hi, any ideas on this for me please?

**Comment by superRaytin** [comment]
I have no idea for this, sorry... :(
